### ISSUE TITLE
The test dataset link in submit google form is training data set link

### ISSUE THREAD

**Issue by dongheehand** [andreas128/NTIRE21_Learning_SR_Space#10]
The test dataset link in submit google form is traning dataset link.
Check the dataset link please
Thank you!

In submit page,
Zip file of super-resolved test images of 4X (We use the latest uploaded file only)
The results have to be in a zip file containing 100x10=1000 super resolutions with name ''{img_idx:06d}_sample{i:05d}.png'' like used in the measure.py file. e.g. 000000_sample00000.png Input: https://data.vision.ee.ethz.ch/alugmayr/NTIRE2021/DIV2K-tr_4X.zip

**Comment by andreas128** [comment]
Thanks, we've updated the form.
