### ISSUE TITLE
Track 4X and Track 8X have mixed train/val data

### ISSUE THREAD

**Issue by usstdqq** [andreas128/NTIRE21_Learning_SR_Space#2]
![Screenshot from 2021-01-14 13-26-26](https://user-images.githubusercontent.com/6977304/104651205-2dd01380-566c-11eb-8bd4-da0fbcf2c0c0.png)
 as shown in the screen shot above, the provided data link/description seems mixed.

**Comment by martin-danelljan** [comment]
Thank you. The links are correct, only the name was wrong. Fixed!
