### ISSUE TITLE
More description in "Spanning of the SR Space"

### ISSUE THREAD

**Issue by FuzhiYang** [andreas128/NTIRE21_Learning_SR_Space#6]
I'm confused of "local_best" and "global_best". Could you give a more description of these two scores? Thank you very much!

**Comment by andreas128** [comment]
We updated the [description](https://github.com/andreas128/NTIRE21_Learning_SR_Space/blob/main/README.md#spanning-of-the-sr-space), is it clear?

The code for the calculation is [here](https://github.com/andreas128/NTIRE21_Learning_SR_Space/blob/470dab96988c64a6033e8a3cf2e060c1ede18d0b/measure.py#L41).

**Comment by FuzhiYang** [comment]
I understood it! Thank you for your quick reply!
