### ISSUE TITLE
I can't open the Sign-up website

### ISSUE THREAD

**Issue by zzhwfy** [andreas128/NTIRE21_Learning_SR_Space#8]
It jumped into _http://bit.ly/3qTbsyd_ but showed no response

**Comment by andreas128** [comment]
It should expand to this link: https://github.us7.list-manage.com/subscribe?u=947bddee8ff33dca6023a20c7&id=933bb48b7f

Please also write me a mail directly.

**Comment by zzhwfy** [comment]
Thank you very much! We have registered with our e-mail using this link
